export const business = {
  name: "La Gaviota Mexican Restaurant",
  shortName: "La Gaviota",
  tagline: "Mexican and Central American food / Comida mexicana y centroamericana",
  phoneDisplay: "303-368-9941",
  phoneHref: "tel:3033689941",
  email: "lagaviotarestaurantaurora@gmail.com",
  emailHref: "mailto:lagaviotarestaurantaurora@gmail.com",
  address: "2280 S Quebec, Denver, CO 80231",
  addressStreet: "2280 S Quebec",
  city: "Denver",
  state: "CO",
  zip: "80231",
  country: "US",
  hours: "Monday-Sunday, 9:00 am-7:00 pm",
  shortHours: "Open daily, 9 am-7 pm",
  mapsQuery: "2280 S Quebec Denver CO 80231",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=2280%20S%20Quebec%2C%20Denver%2C%20CO%2080231",
  mapEmbed:
    "https://www.google.com/maps?q=2280%20S%20Quebec%2C%20Denver%2C%20CO%2080231&output=embed",
  orderPath: "/order",
  url: "https://www.lagaviotadenver.com",
  latitude: 39.67498,
  longitude: -104.90272,
};

export const navItems = [
  { label: "Home", href: "/" },
  { label: "Menu", href: "/menu" },
  { label: "Catering", href: "/catering" },
  { label: "Gallery", href: "/gallery" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const seo = {
  title: "La Gaviota Mexican Restaurant | Mexican & Central American Food in Denver, CO",
  description:
    "Enjoy authentic Mexican and Central American food, tacos, tamales, seafood, pupusas, carryout and party catering at La Gaviota Mexican Restaurant in Denver, CO. Call 303-368-9941.",
  keywords: [
    "Mexican restaurant Denver",
    "Mexican food Denver",
    "Central American food Denver",
    "Pupusas Denver",
    "Salvadoran food Denver",
    "Mexican catering Denver",
    "Tacos Denver",
    "Tamales Denver",
    "Carryout Mexican food Denver",
    "Mexican restaurant South Quebec Denver",
    "Mexican food near 2280 S Quebec",
  ],
};

export type MenuItem = {
  name: string;
  price?: string;
  description?: string;
};

export type MenuCategory = {
  name: string;
  eyebrow?: string;
  description: string;
  image?: string;
  imageAlt?: string;
  featured?: string[];
  items: MenuItem[];
};

export const menuCategories: MenuCategory[] = [
  {
    name: "Tacos La Gaviota",
    eyebrow: "Street tacos",
    description: "Small, fast, flavorful tacos for lunch, carryout or a table full of cravings.",
    featured: ["Tacos Asada $1.89", "Lengua $2.69", "Camaron $4.39"],
    items: [
      { name: "Tacos Asada", price: "$1.89" },
      { name: "Tacos Adobada", price: "$1.89" },
      { name: "Tacos Barbacoa", price: "$1.89" },
      { name: "Tacos Buche", price: "$2.09" },
      { name: "Tacos Carnitas", price: "$1.89" },
      { name: "Tacos Chicharron", price: "$1.89" },
      { name: "Tacos Desebrada", price: "$1.89" },
      { name: "Tacos Lengua", price: "$2.69" },
      { name: "Tacos Pollo", price: "$1.89" },
      { name: "Tacos Camaron", price: "$4.39" },
      { name: "Tacos Pescado", price: "$4.39" },
      { name: "Tacos Tripas", price: "$2.69" },
      { name: "Orden Tacos Crispy", price: "$6.49" },
      { name: "Plato de 3 Tacos", price: "$7.59" },
    ],
  },
  {
    name: "Burritos",
    eyebrow: "Handheld classics",
    description: "Simple burritos with familiar fillings, easy to order and easy to take home.",
    image: "/images/burrito-smothered.webp",
    imageAlt: "Burrito smothered from La Gaviota Mexican Restaurant",
    featured: ["Asada $6.49", "Lengua $7.59", "Frijoles y queso $4.39"],
    items: [
      { name: "Burrito Asada", price: "$6.49" },
      { name: "Burrito Adobada", price: "$6.49" },
      { name: "Burrito Barbacoa", price: "$6.49" },
      { name: "Burrito Carnitas", price: "$6.49" },
      { name: "Burrito Chicharron", price: "$6.49" },
      { name: "Burrito Chorizo", price: "$6.49" },
      { name: "Burrito Chile Relleno", price: "$6.49" },
      { name: "Burrito Desebrada", price: "$6.49" },
      { name: "Burrito Jamon", price: "$6.49" },
      { name: "Burrito Molida", price: "$6.49" },
      { name: "Burrito Pollo", price: "$6.49" },
      { name: "Burrito Frijoles y Queso", price: "$4.39" },
      { name: "Burrito Lengua", price: "$7.59" },
      { name: "Burrito Buche", price: "$7.59" },
    ],
  },
  {
    name: "Burritos Smothered",
    eyebrow: "Covered and comforting",
    description: "Warm smothered burritos with a plate-style feel.",
    image: "/images/burrito-smothered.webp",
    imageAlt: "Smothered burrito plate at La Gaviota Mexican Restaurant",
    featured: ["Asada $7.59", "Lengua $8.69", "Frijol con queso $4.39"],
    items: [
      { name: "Smothered Adobada", price: "$7.59" },
      { name: "Smothered Asada", price: "$7.59" },
      { name: "Smothered Barbacoa", price: "$7.59" },
      { name: "Smothered Carnitas", price: "$7.59" },
      { name: "Smothered Desebrada", price: "$7.59" },
      { name: "Smothered Lengua", price: "$8.69" },
      { name: "Smothered Molida", price: "$7.59" },
      { name: "Smothered Pollo", price: "$7.59" },
      { name: "Smothered Frijol con Queso", price: "$4.39" },
      { name: "Smothered Huevos Papa", price: "$4.39" },
      { name: "Smothered Burrito", price: "$7.59" },
      { name: "Smothered Burrito Chile", price: "$7.59" },
    ],
  },
  {
    name: "Breakfast Burritos",
    eyebrow: "Morning carryout",
    description: "Breakfast burritos and smothered options for a quick start.",
    image: "/images/burrito-smothered.webp",
    imageAlt: "Smothered burrito from La Gaviota",
    featured: ["Grande $4.39", "Smothered $5.59", "Frijoles y queso $3.29"],
    items: [
      { name: "Burrito Smothered", price: "$5.59" },
      { name: "Burrito Grande Bacon", price: "$4.39" },
      { name: "Burrito Grande Chorizo", price: "$4.39" },
      { name: "Burrito Tocino", price: "$4.39" },
      { name: "Burrito Grande Ham", price: "$4.39" },
      { name: "Burrito Grande Huevos Papa", price: "$4.39" },
      { name: "Burrito Frijoles y Queso", price: "$3.29" },
      { name: "Burrito Smothered Bacon", price: "$5.59" },
      { name: "Burrito Smothered Chorizo", price: "$5.59" },
    ],
  },
  {
    name: "Platos de Desayuno",
    eyebrow: "Breakfast plates",
    description: "Eggs, chilaquiles, tamales and warm breakfast plates.",
    image: "/images/desayuno-salvadoreno.webp",
    imageAlt: "Desayuno salvadoreno served at La Gaviota",
    featured: ["Huevos rancheros $7.99", "Chilaquiles $10.99", "Desayuno salvadoreno $10.99"],
    items: [
      { name: "Desayuno Chorizo", price: "$8.69" },
      { name: "Desayuno Jamon", price: "$8.69" },
      { name: "Desayuno Tocino", price: "$8.69" },
      { name: "Huevos Rancheros", price: "$7.99" },
      { name: "Plato Chilaquiles", price: "$10.99" },
      { name: "Plato Chilaquiles Rojos", price: "$10.99" },
      { name: "Desayuno Salvadoreno", price: "$10.99" },
      { name: "Tamales Smothered", price: "$6.49" },
      { name: "Combination Desayuno", price: "$10.99" },
      { name: "Chuletas a la Plancha", price: "$9.99" },
      { name: "Desayuno Hondureno", price: "$10.99" },
      { name: "Papas, Queso y Huevo", price: "$8.63" },
    ],
  },
  {
    name: "Plates",
    eyebrow: "Full plates",
    description: "Big plates for sitting down, sharing, or taking home for dinner.",
    image: "/images/fajitas-combinadas.webp",
    imageAlt: "Fajitas combinadas plate from La Gaviota",
    featured: ["Alambre $12.49", "Birria chivo $17.29", "Fajitas $15.99"],
    items: [
      { name: "Alambre", price: "$12.49" },
      { name: "Birria de Chivo", price: "$17.29" },
      { name: "Caldo de Res", price: "$11.79" },
      { name: "Chile Rellenos", price: "$11.79" },
      { name: "Carne Asada", price: "$14.09" },
      { name: "Fajitas Pollo y Carne", price: "$13.49" },
      { name: "Fajitas Res", price: "$13.49" },
      { name: "Fajitas Pollo", price: "$12.89" },
      { name: "Carnitas", price: "$10.29" },
      { name: "Flautas Desebrada", price: "$8.69" },
      { name: "Pechuga Empanizada", price: "$11.79" },
      { name: "Bistec a la Mexicana", price: "$11.79" },
      { name: "Pozole Blanco", price: "$11.79" },
      { name: "Pozole Rojo", price: "$11.79" },
      { name: "Menudo con Tortilla", price: "$11.79" },
      { name: "Menudo con Pan", price: "$11.79" },
      { name: "Enchiladas Verde", price: "$9.99" },
      { name: "Enchiladas Rojo", price: "$9.99" },
      { name: "Quesadilla Harina", price: "$8.69" },
      { name: "Quesadillas Maiz", price: "$3.79" },
      { name: "Flautas de Pollo", price: "$8.99" },
      { name: "Costillas Salsa Verde", price: "$10.29" },
      { name: "Bistec Ranchero", price: "$11.79" },
      { name: "Chicharron Guisado", price: "$10.79" },
      { name: "Mole de Pollo", price: "$8.69" },
      { name: "Nachos", price: "$9.99" },
      { name: "Barbacoa", price: "$12.99" },
      { name: "Fajitas", price: "$15.99" },
      { name: "T-Bone Steak", price: "$15.99" },
      { name: "Milanesa de Res", price: "$14.09" },
    ],
  },
  {
    name: "Gorditas",
    eyebrow: "Antojitos",
    description: "Filled gorditas with asada, barbacoa, rajas, pollo and more.",
    image: "/images/gorditas-de-asada.webp",
    imageAlt: "Gorditas de asada from La Gaviota",
    featured: ["Most fillings $2.99", "Lengua $4.99", "Harina $2.99"],
    items: [
      { name: "Gordita Rellena Adobada", price: "$2.99" },
      { name: "Gordita Rellena Asada", price: "$2.99" },
      { name: "Gordita Rellena Barbacoa", price: "$2.99" },
      { name: "Gordita Rellena Carnitas", price: "$2.99" },
      { name: "Gordita Rellena", price: "$2.50" },
      { name: "Gordita Rellena Lengua", price: "$4.99" },
      { name: "Gordita Rellena Molida", price: "$2.99" },
      { name: "Gordita Rellena Rajas", price: "$2.99" },
      { name: "Gordita Rellena Buche", price: "$2.99" },
      { name: "Gordita Rellena Chorizo", price: "$2.99" },
      { name: "Gordita Rellena Desebrada", price: "$2.99" },
      { name: "Gordita Rellena Frijoles", price: "$2.99" },
      { name: "Gordita Rellena Milanesa", price: "$2.99" },
      { name: "Gordita Rellena Pollo", price: "$2.99" },
      { name: "Gordita de Harina", price: "$2.99" },
    ],
  },
  {
    name: "Seafood",
    eyebrow: "Mariscos",
    description: "Shrimp, fish, seafood soups, ceviche and coastal plates.",
    image: "/images/siete-mares.webp",
    imageAlt: "Siete mares seafood soup at La Gaviota",
    featured: ["7 Mares $18.39", "Coctel $12.89", "Mojarra $15.19"],
    items: [
      { name: "7 Mares", price: "$18.39" },
      { name: "Caldo Camaron", price: "$16.25" },
      { name: "Caldo Camaron y Pescado", price: "$17.29" },
      { name: "Camarones a la Diabla", price: "$16.29" },
      { name: "Mar y Tierra", price: "$18.39" },
      { name: "Camarones al Mojo de Ajo", price: "$16.29" },
      { name: "Filete Pescado", price: "$15.19" },
      { name: "Coctel Camarones", price: "$12.89" },
      { name: "Tostada Camaron", price: "$5.69" },
      { name: "Mojarra", price: "$15.19" },
      { name: "Caldo Pescado", price: "$16.29" },
      { name: "Empanadas de Camaron", price: "$14.09" },
      { name: "Tortitas de Camarones", price: "$7.99" },
      { name: "Filete Empanizado", price: "$15.12" },
      { name: "Tostada Ensalada de Camaron", price: "$1.99" },
    ],
  },
  {
    name: "Pupusas",
    eyebrow: "Central American favorites",
    description: "Pupusas for the table, all listed at one easy price.",
    image: "/images/pupusas.webp",
    imageAlt: "Pupusas served at La Gaviota Mexican Restaurant",
    featured: ["All listed $2.99"],
    items: [
      { name: "Pupusa Chicharron", price: "$2.99" },
      { name: "Pupusa Frijol", price: "$2.99" },
      { name: "Pupusa Queso con Loroco", price: "$2.99" },
      { name: "Pupusa Revuelta", price: "$2.99" },
      { name: "Pupusa Frijol y Queso", price: "$2.99" },
      { name: "Pupusa Carne Asada", price: "$2.99" },
      { name: "Queso sin Loroco", price: "$2.99" },
      { name: "Pupusa Chicharron y Queso", price: "$2.99" },
    ],
  },
  {
    name: "Sopes",
    eyebrow: "Loaded masa bites",
    description: "Sopes with beans, meats, cheese and classic toppings.",
    image: "/images/sopes.webp",
    imageAlt: "Sopes de asada from La Gaviota",
    featured: ["Frijol $3.29", "Asada $4.39", "Buche $4.30"],
    items: [
      { name: "Sope Frijol", price: "$3.29" },
      { name: "Sope Asada", price: "$4.39" },
      { name: "Sope Barbacoa", price: "$4.39" },
      { name: "Sope Buche", price: "$4.30" },
      { name: "Sope Carnitas", price: "$4.39" },
      { name: "Sope Chicharron", price: "$4.39" },
      { name: "Sope Chorizo", price: "$4.39" },
      { name: "Sope Desebrada", price: "$4.39" },
      { name: "Sope Jamon", price: "$4.39" },
      { name: "Sope Milanesa", price: "$4.39" },
      { name: "Sope Pollo", price: "$4.39" },
      { name: "Sope Frijol y Queso", price: "$4.39" },
      { name: "Sope Adobado", price: "$4.39" },
      { name: "Sope Molida", price: "$4.39" },
    ],
  },
  {
    name: "Tortas",
    eyebrow: "Bolillo sandwiches",
    description: "Hearty tortas with meats, milanesa, pambazo and Cubana options.",
    image: "/images/torta.webp",
    imageAlt: "Torta from La Gaviota Mexican Restaurant",
    featured: ["Most tortas $8.69", "Lengua $9.99", "Cubana $10.79"],
    items: [
      { name: "Torta Asada", price: "$8.69" },
      { name: "Torta Adobada", price: "$8.69" },
      { name: "Torta Barbacoa", price: "$8.69" },
      { name: "Torta Buche", price: "$8.69" },
      { name: "Torta Carnitas", price: "$8.69" },
      { name: "Torta Chicharron", price: "$8.69" },
      { name: "Torta Chorizo", price: "$8.69" },
      { name: "Torta Desebrada", price: "$8.69" },
      { name: "Torta Jamon", price: "$8.69" },
      { name: "Torta Lengua", price: "$9.99" },
      { name: "Torta de Milanesa", price: "$8.69" },
      { name: "Torta Pollo", price: "$8.69" },
      { name: "Torta Ahogada", price: "$8.69" },
      { name: "Torta Cubana", price: "$10.79" },
      { name: "Torta Pambazo", price: "$6.49" },
    ],
  },
  {
    name: "Tostadas",
    eyebrow: "Crispy antojitos",
    description: "Crunchy tostadas with beans, meat and seafood options.",
    image: "/images/tostadas-de-asada.webp",
    imageAlt: "Tostadas de asada served at La Gaviota",
    featured: ["Frijol $2.99", "Asada $3.99", "Lengua $4.99"],
    items: [
      { name: "Tostada Frijol", price: "$2.99" },
      { name: "Tostada Asada", price: "$3.99" },
      { name: "Tostada Chicharron", price: "$3.99" },
      { name: "Tostada Adobada", price: "$3.99" },
      { name: "Tostada Barbacoa", price: "$3.99" },
      { name: "Tostada Buche", price: "$4.99" },
      { name: "Tostada Carnitas", price: "$3.99" },
      { name: "Tostada Chorizo", price: "$3.99" },
      { name: "Tostada Desebrada", price: "$3.99" },
      { name: "Tostada Lengua", price: "$4.99" },
      { name: "Tostada Molida", price: "$3.99" },
      { name: "Tostada Pollo", price: "$3.99" },
      { name: "Tostadas de Atun", price: "$5.99" },
    ],
  },
  {
    name: "Combos",
    eyebrow: "Plates to fill up",
    description: "Simple combo plates from the current menu.",
    image: "/images/carne-asada.webp",
    imageAlt: "Carne asada plate at La Gaviota Mexican Restaurant",
    featured: ["Carnitas $11.99", "Pollo asado $11.99", "Carne asada $15.99"],
    items: [
      { name: "Combo Carnitas", price: "$11.99" },
      { name: "Combo Pollo Asado", price: "$11.99" },
      { name: "Combo Carne Asada", price: "$15.99" },
    ],
  },
  {
    name: "Sides",
    eyebrow: "For the table",
    description: "Tamales, rice, beans, tortillas, salsa and sides for sharing.",
    image: "/images/salsa-bar.webp",
    imageAlt: "La Gaviota salsa bar with fresh salsa choices",
    featured: ["Tamales $1.79", "Docena $15.19", "Side arroz $2.19"],
    items: [
      { name: "Docena de Tamales", price: "$15.19" },
      { name: "Media Docena de Tamales", price: "$7.59" },
      { name: "Side French Fries", price: "$2.14" },
      { name: "Libra de Arroz", price: "$3.19" },
      { name: "Vaso Grande Arroz", price: "$5.89" },
      { name: "Side de Frijoles", price: "$2.19" },
      { name: "Libra de Frijoles", price: "$3.79" },
      { name: "Vaso Frijoles Grande", price: "$6.49" },
      { name: "Tamales Pollo", price: "$1.79" },
      { name: "Tamales Puerco", price: "$1.79" },
      { name: "Tamale Raja", price: "$1.82" },
      { name: "Plato Tamales", price: "$6.46" },
      { name: "Plato Tamales Smothered", price: "$6.49" },
      { name: "Vaso Salsa Chica Variedad", price: "$4.39" },
      { name: "Vaso Grande de Salsa", price: "$8.59" },
      { name: "Tortilla Harina", price: "$1.39" },
      { name: "Tortilla Maiz", price: "$1.35" },
      { name: "Side Arroz", price: "$2.19" },
    ],
  },
  {
    name: "Extras",
    eyebrow: "Add-ons",
    description: "Extra meats, tortillas, crema, cheese and small sides.",
    featured: ["Queso $0.54", "Crema $1.08", "Carne asada $4.30"],
    items: [
      { name: "Libra de Barbacoa", price: "$12.95" },
      { name: "Media Libra", price: "$5.94" },
      { name: "Media Libra Carnitas", price: "$5.94" },
      { name: "Libra Carnitas", price: "$9.71" },
      { name: "Chips", price: "$3.29" },
      { name: "Extra Tomate", price: "$1.08" },
      { name: "Extra Queso", price: "$0.54" },
      { name: "Huevos Estrellado", price: "$1.06" },
      { name: "Extra Aguacate", price: "$1.94" },
      { name: "Side Carne", price: "$4.30" },
      { name: "Extra Carne Asada", price: "$4.30" },
      { name: "Una Enchilada", price: "$2.99" },
      { name: "Una Enchilada Roja", price: "$2.99" },
      { name: "Extra Smothered", price: "$1.08" },
      { name: "Extra Crema", price: "$1.08" },
      { name: "Tortilla Extra", price: "$1.06" },
      { name: "Extra Pollo", price: "$4.30" },
      { name: "Extra Bolillo", price: "$1.09" },
      { name: "Tortillas a Mano", price: "$1.93" },
      { name: "Tortillas Harina", price: "$1.39" },
    ],
  },
  {
    name: "Postres",
    eyebrow: "Sweet finish",
    description: "Classic desserts, ice cream, fruit treats and candies.",
    featured: ["Flan $3.29", "Churros $1.06", "Mangoneadas $3.09"],
    items: [
      { name: "Cake", price: "$3.22" },
      { name: "Flan", price: "$3.29" },
      { name: "Gelatina", price: "$2.79" },
      { name: "Arroz con Leche", price: "$2.43" },
      { name: "Paletas", price: "$1.89" },
      { name: "Boli", price: "$1.89" },
      { name: "Donas de Pan", price: "$1.06" },
      { name: "Postres de Fruta", price: "$3.22" },
      { name: "Cheesecake", price: "$2.14" },
      { name: "Capirotada", price: "$4.99" },
      { name: "Platanos Postre", price: "$6.46" },
      { name: "Mangoneadas", price: "$3.09" },
      { name: "Churros", price: "$1.06" },
      { name: "Ice Cream", price: "$4.30" },
    ],
  },
  {
    name: "Drinks",
    eyebrow: "Aguas, beer and cafe",
    description: "Aguas frescas, coffee, beer, micheladas and cold drinks.",
    image: "/images/salsa-bar.webp",
    imageAlt: "Salsa bar and drink-friendly dishes at La Gaviota",
    featured: ["Michelada $7.59", "Horchata $2.49+", "Jamaica $3.29"],
    items: [
      { name: "Cerveza Bote", price: "$3.09" },
      { name: "Cerveza Botella", price: "$3.49" },
      { name: "Cerveza Familiar", price: "$6.79" },
      { name: "Michelada", price: "$7.59" },
      { name: "Horchata Chica", price: "$2.49" },
      { name: "Horchata Large", price: "$3.29" },
      { name: "Soda Chica / Mixed", price: "$2.19" },
      { name: "Coca Grande", price: "$3.09" },
      { name: "Cafe Negro", price: "$1.69" },
      { name: "Boing Soda", price: "$2.69" },
      { name: "Champurrado Chico", price: "$3.29" },
      { name: "Jamaica Large", price: "$3.29" },
      { name: "Tamarindo Large", price: "$3.29" },
      { name: "Agua Natural", price: "$1.69" },
      { name: "Jugo de Coco", price: "$2.19" },
      { name: "Gatorade", price: "$2.19" },
      { name: "Champurrado Grande", price: "$5.39" },
      { name: "Cafe con Leche", price: "$1.89" },
    ],
  },
];

export const menuHighlights = [
  { name: "Fajitas combinadas", price: "$13.49", image: "/images/fajitas-combinadas.webp" },
  { name: "Pupusas", price: "$2.99", image: "/images/pupusas.webp" },
  { name: "Tostadas de asada", price: "$3.99", image: "/images/tostadas-de-asada.webp" },
  { name: "Tortas", price: "$8.69", image: "/images/torta.webp" },
  { name: "7 Mares", price: "$18.39", image: "/images/siete-mares.webp" },
  { name: "Chilaquiles", price: "$10.99", image: "/images/chilaquiles.webp" },
];

export const cateringOccasions = [
  "Parties",
  "Anniversaries",
  "Graduations",
  "Birthdays",
  "Family gatherings",
  "Special occasions",
];

export const faqs = [
  {
    question: "Do you offer carryout?",
    answer: "Yes. Call 303-368-9941 to pre-order your carryout.",
  },
  {
    question: "Do you offer catering?",
    answer:
      "Yes. La Gaviota offers Mexican and Central American food catering for parties, anniversaries, graduations, birthdays and special occasions.",
  },
  {
    question: "How do I order catering?",
    answer: "Call 303-368-9941 and ask about catering or party packages.",
  },
  {
    question: "What kind of food is on the menu?",
    answer:
      "The menu includes tacos, burritos, breakfast plates, gorditas, seafood, pupusas, sopes, tortas, tostadas, sides, desserts and drinks, with prices shown from the existing La Gaviota menu.",
  },
  {
    question: "Where are you located?",
    answer: "La Gaviota Mexican Restaurant is located at 2280 S Quebec, Denver, CO 80231.",
  },
  {
    question: "What are your business hours?",
    answer: "Monday through Sunday, 9:00 am to 7:00 pm.",
  },
  {
    question: "Do you have dine-in?",
    answer: "Yes. Guests can dine in at the restaurant, and carryout is also available.",
  },
  {
    question: "Do you show soccer?",
    answer:
      "The restaurant has a casual dining room. Call ahead if you are planning to watch a specific game.",
  },
];

export const galleryImages = [
  {
    src: "/images/fajitas-combinadas.webp",
    avif: "/images/fajitas-combinadas.avif",
    alt: "Fajitas combinadas served at La Gaviota Mexican Restaurant in Denver",
    title: "Fajitas combinadas",
    featured: true,
  },
  {
    src: "/images/alambre.webp",
    avif: "/images/alambre.avif",
    alt: "Alambre plate from La Gaviota Mexican Restaurant in Denver",
    title: "Alambre",
  },
  {
    src: "/images/camarones-diabla.webp",
    avif: "/images/camarones-diabla.avif",
    alt: "Camarones a la diabla seafood plate at La Gaviota",
    title: "Camarones a la diabla",
  },
  {
    src: "/images/torta.webp",
    avif: "/images/torta.avif",
    alt: "Torta from La Gaviota Mexican Restaurant in Denver",
    title: "Torta",
  },
  {
    src: "/images/pupusas.webp",
    avif: "/images/pupusas.avif",
    alt: "Pupusas served at La Gaviota Mexican Restaurant",
    title: "Pupusas",
  },
  {
    src: "/images/sopes.webp",
    avif: "/images/sopes.avif",
    alt: "Sopes de asada from La Gaviota Mexican Restaurant",
    title: "Sopes de asada",
  },
  {
    src: "/images/birria.webp",
    avif: "/images/birria.avif",
    alt: "Birria de chivo from La Gaviota Mexican Restaurant",
    title: "Birria de chivo",
  },
  {
    src: "/images/burrito-smothered.webp",
    avif: "/images/burrito-smothered.avif",
    alt: "Burrito smothered from La Gaviota Mexican Restaurant",
    title: "Burrito smothered",
  },
  {
    src: "/images/salsa-bar.webp",
    avif: "/images/salsa-bar.avif",
    alt: "La Gaviota salsa bar with fresh salsa choices",
    title: "Salsa bar",
  },
  {
    src: "/images/siete-mares.webp",
    avif: "/images/siete-mares.avif",
    alt: "Siete mares seafood soup from La Gaviota Mexican Restaurant",
    title: "Siete mares",
  },
  {
    src: "/images/chilaquiles.webp",
    avif: "/images/chilaquiles.avif",
    alt: "Chilaquiles breakfast plate at La Gaviota Mexican Restaurant",
    title: "Chilaquiles",
  },
  {
    src: "/images/mojarra-frita.webp",
    avif: "/images/mojarra-frita.avif",
    alt: "Mojarra frita seafood plate from La Gaviota",
    title: "Mojarra frita",
  },
  {
    src: "/images/pambazo.webp",
    avif: "/images/pambazo.avif",
    alt: "Pambazo from La Gaviota Mexican Restaurant",
    title: "Pambazo",
  },
  {
    src: "/images/tostadas-de-asada.webp",
    avif: "/images/tostadas-de-asada.avif",
    alt: "Tostadas de asada from La Gaviota Mexican Restaurant",
    title: "Tostadas de asada",
  },
  {
    src: "/images/gorditas-de-asada.webp",
    avif: "/images/gorditas-de-asada.avif",
    alt: "Gorditas de asada from La Gaviota Mexican Restaurant",
    title: "Gorditas de asada",
  },
  {
    src: "/images/enchiladas-de-pollo.webp",
    avif: "/images/enchiladas-de-pollo.avif",
    alt: "Enchiladas de pollo from La Gaviota Mexican Restaurant",
    title: "Enchiladas de pollo",
  },
  {
    src: "/images/desayuno-salvadoreno.webp",
    avif: "/images/desayuno-salvadoreno.avif",
    alt: "Desayuno salvadoreno served at La Gaviota",
    title: "Desayuno salvadoreno",
  },
  {
    src: "/images/ceviche-de-camaron.webp",
    avif: "/images/ceviche-de-camaron.avif",
    alt: "Ceviche de camaron from La Gaviota Mexican Restaurant",
    title: "Ceviche de camaron",
  },
  {
    src: "/images/coctel-de-camarones.webp",
    avif: "/images/coctel-de-camarones.avif",
    alt: "Coctel de camarones from La Gaviota Mexican Restaurant",
    title: "Coctel de camarones",
  },
  {
    src: "/images/camarones-empanizados.webp",
    avif: "/images/camarones-empanizados.avif",
    alt: "Camarones empanizados from La Gaviota Mexican Restaurant",
    title: "Camarones empanizados",
  },
  {
    src: "/images/caldo-de-res.webp",
    avif: "/images/caldo-de-res.avif",
    alt: "Caldo de res from La Gaviota Mexican Restaurant",
    title: "Caldo de res",
  },
  {
    src: "/images/camarones-al-mojo-de-ajo.webp",
    avif: "/images/camarones-al-mojo-de-ajo.avif",
    alt: "Camarones al mojo de ajo from La Gaviota Mexican Restaurant",
    title: "Camarones al mojo de ajo",
  },
  {
    src: "/images/caldo-de-camaron-y-pescado.webp",
    avif: "/images/caldo-de-camaron-y-pescado.avif",
    alt: "Caldo de camaron y pescado from La Gaviota",
    title: "Caldo de camaron y pescado",
  },
];
